name: Deploy new version
run-name: ${{ gitea.actor }} is deploying a new version of the UI
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - run: 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - run: eval $(ssh-agent -s)
      - run: mkdir -p ~/.ssh
      - run: chmod 700 ~/.ssh
      - run: echo "$SSH_PRIVATE_KEY" | base64 -di > ~/.ssh/id_rsa
      - run: chmod 400 ~/.ssh/id_rsa
      - run: ssh-keyscan $SSH_HOST > ~/.ssh/known_hosts
      - run: chmod 644 ~/.ssh/known_hosts
      - run: ssh $SSH_USER@$SSH_HOST "cd /opt/discord-bots/bakalariStalkinWebUI && git pull"
      - run: ssh $SSH_USER@$SSH_HOST "cd /opt/discord-bots/bakalariStalkinWebUI && PATH=$PATH:/home/runnerBoi/.nvm/versions/node/v18.0.0/bin npm run build"
      - run: ssh $SSH_USER@$SSH_HOST "sudo systemctl restart web-bakalariStalinWebUI.service"
